version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test-output:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Test basic output
          command: |
            echo 'Testing output'
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: run unit tests
          command: |
            npm install && npm test
      - codecov/upload:
          file: "./coverage/clover.xml"
          token: f5dfcd1f-db14-4d13-9dd8-7d84fff0a594
workflows:
  version: 2
  Example_Workflow:
    jobs:
      - test-output
      - build
